#!/usr/bin/env python3
#
# basically:
#curl -X POST \
#  -H 'Authorization: '$OLCF_TOKEN \
#  -H 'Content-Type: application/json' \
#  -d @'{{base}}/scripts/job' \
#  https://s3m.apps.olivine.ccs.ornl.gov/slurm/v0.0.41/defiant/job/submit
#
# except that job is yaml-formatted.
#
import sys
import os
import asyncio
import json

import yaml
import aiohttp

async def main(job, token):
    base_url = "https://s3m.apps.olivine.ccs.ornl.gov/slurm/v0.0.41/"
    headers = { "Authorization": token,
                "Content-Type": "application/json"
              }
    async with aiohttp.ClientSession(base_url=base_url, headers=headers) as session:
        async with session.post("defiant/job/submit", json=job) as resp:
            print(resp.status)
            print(await resp.text())

if __name__=="__main__":
    argv = sys.argv

    jobndx = int(argv[1])
    with open("{{base}}/scripts/job") as f:
        job = yaml.safe_load(f)
        job['script'] = job['script'] % { 'jobndx': jobndx }

    token = os.getenv("OLCF_TOKEN")
    if token is None:
        raise ValueError("OLCF_TOKEN env var must be defined")
    print("submitting job:")
    print( json.dumps(job, indent=2) )

    asyncio.run(main(job, token))
